### PR TITLE
Change over to updates.drupal.org backend for dupal versions

### LINKED ISSUE #281: Switch to updates.drupal.org for Drupal backend
Drupal uses urls like:
https://updates.drupal.org/release-history/wysiwyg/6.x
to check for updates. The urls are formatted like:
```https://updates.drupal.org/release-history/<project>/<api version>```
and return an xml response with the release history, this will also solve all the [failed updates](https://release-monitoring.org/projects/updates/failed) that are related to drupal6 (I think).

### PR DESCRIPTION
**Pull request by daveol**
This is a pull request to fix #281

### CODE REVIEW

**Comment by pypingou** [comment]
Cool, that looks simple enough :)

Does it need any change in the test suite?

**Comment by daveol** [comment]
I don't know I'll take a look.... The commit was made using the github editor (web interface)

**Comment by daveol** [comment]
hmm... it seems to fail: [log](https://gist.github.com/38cdea1a1620af77b66ba1b50b579a73)

**Comment by daveol** [comment]
I fixed the unit-tests

**Comment by pypingou** [comment]
Cool, thanks!

**Pull request merged**
