### PR TITLE
Add SourceHut backend

### PR DESCRIPTION
**Pull request by erolkskn**
- Created SourceHut backend.
- Resolves: #999

### CODE REVIEW

**Review by Zlopez — CHANGES_REQUESTED** [review]
I will wait till all the tests will pass.

Also could you update documentation as well? There is a description of all backends in one section of user guide.

**Review by Zlopez — APPROVED** [review]

**Comment by Zlopez** [comment]
Sorry this was taking so long, I was on vacation.

**Comment by erolkskn** [comment]
> Sorry this was taking so long, I was on vacation.

Not a problem, i hope you enjoyed your vacation :-)

**Comment by Zlopez** [comment]
> > Sorry this was taking so long, I was on vacation.
> 
> Not a problem, i hope you enjoyed your vacation :-)

Yeah, it was great :-)

**Pull request merged**
