### PR TITLE
Modified name in github project backend

### PR DESCRIPTION
**Pull request by Aayush-Kasurde**
Fixes issue #115

### CODE REVIEW

**Comment by pypingou** [comment]
I merged but it broke the unit-tests, would you like to have a look at fixing them?

**Comment by pypingou** [comment]
@Aayush-Kasurde I realized today that you did not sign the FPCA in the Fedora account system, could you please confirm that you gave us permission to use this change under the same license terms as the rest of the code in the project ?

Thanks

**Comment by Aayush-Kasurde** [comment]
@pypingou I have completed FPCA form on FAS. I give you permission to use this change under same licence terms as the rest of code in the project.
Thanks and regards

**Comment by pypingou** [comment]
On Thu, Jun 25, 2015 at 08:37:16AM -0700, Aayush wrote:
>    @pypingou I have completed FPCA form on FAS. I give you permission to use
>    this change under same licence terms as the rest of code in the project.
>    Thanks and regards

Many thanks for the acknowledgment! :)

**Pull request merged**
