### PR TITLE
Stackage: change regexp to track LTS Haskell

### PR DESCRIPTION
**Pull request by juhp**
previous regexp was not tracking nightly but actually very latest package in Hackage!

### CODE REVIEW

**Comment by pypingou** [comment]
Did you run the tests on this?

**Comment by juhp** [comment]
> Did you run the tests on this?

Okay I just tried on my machine and got:

```
E
======================================================================
ERROR: Failure: ImportError (No module named vcr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/petersen/src/anitya/tests/__init__.py", line 33, in <module>
    import vcr
ImportError: No module named vcr
```

Am I missing something?

Would it be possible to setup travis CI to run the tests automatically?

**Comment by pypingou** [comment]
We have jenkins but it only works for changes in the repo, not on pull-requests (could look how to set this up though)

**Comment by juhp** [comment]
Any hints/clues about the above vcr error?

**Comment by pypingou** [comment]
I guess a missing dependency on https://admin.fedoraproject.org/pkgdb/package/python-vcrpy/

**Comment by juhp** [comment]
(Yep, sorry!  Somehow I had forgot to install test_requirements.txt: thought i had.)

Okay Stackage tests pass with d558137. :)

**Comment by pypingou** [comment]
Let's merge this, thanks @juhp !

**Pull request merged**
