### PR TITLE
Remove non-working script tags

### PR DESCRIPTION
**Pull request by tyll**
Remove script tags with sources to non-existent files. JQuery is already
included in master template.

### CODE REVIEW

**Comment by ralphbean** [comment]
How about jQuery-UI?  Is it already included.

I'm not sure what we actually rely on and will wait for @pypingou to comment.

**Comment by tyll** [comment]
On Fri, Feb 20, 2015 at 03:47:41PM -0800, Ralph Bean wrote:
> How about jQuery-UI?  Is it already included.
> 
> I'm not sure what we actually rely on and will wait for @pypingou to comment.

It is not in the repo and also not deployed on release-monitoring.org.
But if it is needed, the path needs to be adjusted to include js/, if it
should match the jquery javascript file that is already used.

**Comment by ralphbean** [comment]
> It is not in the repo and also not deployed on release-monitoring.org

Sounds good to me.  :+1: here.

**Comment by pypingou** [comment]
Thanks!

**Pull request merged**
