### PR TITLE
Fix the unit-tests for the stackage backend

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by oddshocks** [comment]
:+1:

**Comment by pypingou** [comment]
Apparently not yet, jenkins isn't happy :)

**Comment by pypingou** [comment]
Ok, so if @juhp could have a look at it, there is something odd with jenkins: http://jenkins.cloud.fedoraproject.org/job/anitya/

**Comment by juhp** [comment]
Hmm sorry about all that - I confess I didn't test...

http://jenkins.cloud.fedoraproject.org/job/anitya/lastUnsuccessfulBuild/consoleText

**Comment by juhp** [comment]
How can I reproduce this locally on my machine?
I followed the instructions from README.rst but don't get the above (cpphs) error.

How about merging the fix_unit-tests branch anyway? - nothing to lose I think. :)

**Comment by pypingou** [comment]
Ok so for a reason I do not understand nor could reproduce, jenkins didn't manage to call the stackage server.
Thanks to @ralphbean we're now using the VCR library that allows caching the requested page, so I've added these cache files and now jenkins is happy.

My only wonder is if the files `` tests/tests/request-data/__main__.*`` are needed :)

**Comment by ralphbean** [comment]
> My only wonder is if the files tests/tests/request-data/__main__.* are needed :)

That may depend on how the tests were run?  I.e. if you run the file directly versus using ``nosetests``, I bet the name of the module is different (i.e., it gets ``__main__`` prefixed).

**Comment by ralphbean** [comment]
Easy way to tell:  delete them and re-run the tests with ``runtests.sh``.  If they don't come back, then they're not needed.

**Comment by pypingou** [comment]
So indeed it's not needed :), removed!

**Comment by ralphbean** [comment]
:100:

**Pull request merged**
