### PR TITLE
More info when mapping a project fails

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by ralphbean** [comment]
Can we provide a link to the other project so people can go inspect it?

**Comment by pypingou** [comment]
I thought about this but it'll appear escaped.

We could turn off autoescape for flash messages I guess

**Comment by pypingou** [comment]
Hm, looking further, this will be hard as the error message is generated in the backend library which has thus not access to flask :-/

**Comment by ralphbean** [comment]
Oh well, then.  :+1:

**Comment by ralphbean** [comment]
Much better.  Thanks!  :+1:

**Pull request merged**
