### PR TITLE
Added fix for issue #107

### PR DESCRIPTION
**Pull request by Aayush-Kasurde**
Converted Google project name to lower case using lower()

### CODE REVIEW

**Comment by pypingou** [comment]
Hi,

Thanks for the fix, couple of remarks:

a/ This will not fix the use case of #107 because now it will just take the ``project.name.lower()`` so it's as if the user had entered in anytia the project name in lower case. 
It only needs fixing in the URL not for the regex.

b/ The commit message is good, but you just inverted.
The first line should be : ``Converted Google project name to lower case using lower()`` and lower down you would have ``Fixes issue #107``
Otherwise the first thing you see when reading the log of the project is ``Added fix for issue_107`` which is not really descriptive of what the change is (unless you know by heart every issue of the project).

**Comment by Aayush-Kasurde** [comment]
a/ Could you please elaborate more ?

b/ Totally Agree. I will take care of this in future.

**Comment by pypingou** [comment]
See in #107 (the first post, the original issue) what is a good and a bad URL and see how the sources are named ;-)

**Comment by cicku** [comment]
It's better to squash into one commit.

**Comment by pypingou** [comment]
And it would allow to adjust the commit message :)

Also, you could change only one line, no real need to keep the projectname variable :)

**Pull request closed without merging**
