### PR TITLE
Improve the edit endpoint to allow showing the examples and extra infos

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by puiterwijk** [comment]
Looks sane to me, but maybe you want to set this on the global template level?

**Comment by puiterwijk** [comment]
Never mind the global level remark, looking closer this isn't passed to a lot of templates.
:+1:

**Comment by vivekanand1101** [comment]
I tested on mine, it works :+1:

**Comment by pypingou** [comment]
Thanks for the review folks

**Pull request merged**
