### PR TITLE
Check now button available after an edit

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by pypingou** [comment]
Fixes https://github.com/fedora-infra/anitya/issues/65 as well

**Comment by ralphbean** [comment]
Will this allow me to look at any project and manually tack ``?justedit=True`` in the url in order to get an edit button?

**Comment by pypingou** [comment]
No the value is set in the session after having press 'Update' in the edit page

**Comment by ralphbean** [comment]
Well, :+1: then.

**Pull request merged**
