### PR TITLE
Run docker image on Travis and update it (F32, Flask, Ansible bootstrap)

### PR DESCRIPTION
**Pull request by abitrolly**
This adds a couple of fixes to containerized Anitya. In the final form, it should be possible to do this.
```
$ podman build -t anitya .
$ podman run -it -p 8080:80 anitya
```
http://127.0.0.1:8080

---

This PR replaces Apache with Flask, removes the remains of Apache config, and reuses Ansible playbooks for Vagrant for setting up Docker image.

### CODE REVIEW

**Comment by Zlopez** [comment]
Is this now ready for merging?

**Comment by abitrolly** [comment]
@Zlopez should be ready to be merged once tests pass. I still haven't figured out all the bits to run Anitya. After this PR is merged, only Ansible playbooks need to be tweaked for that to happen.

**Review by Zlopez — CHANGES_REQUESTED** [review]
Looks good and even the tests are going through. Could you just squash the commits?

**Comment by abitrolly** [comment]
Done squashing. Tests doesn't touch Ansible playbooks. Current playbooks can only be tested by remaking `vagrant up` locally, but `vagrant up` didn't work for me and I haven't found the time to report the bugs with `libvirt` that occurred.

**Comment by Zlopez** [comment]
I'm using vagrant up for daily work on Anitya, if you are talking about provisioning playbooks, I can confirm they are working.

**Comment by Zlopez** [comment]
But I didn't tried your changes, let me check.

**Comment by Zlopez** [comment]
I tried `vagrant up` on your PR and it's working without issue. :+1:

**Review by Zlopez — APPROVED** [review]

**Pull request merged**
