### PR TITLE
project page: Remove fixed column widths

### PR DESCRIPTION
**Pull request by ferdnyc**
Many project pages contain URLs, which push out the width of the left column and leave the page looking like this:

image

<s>Instead of wasting one layout column on each side with offsets (padding), give the left column all 7 spaces of layout width available, leaving the        other 5 for the right column. </s>

See updated details and screenshots below.

### CODE REVIEW

**Comment by ferdnyc** [comment]
> Build failed. More information on how to proceed and troubleshoot errors available at https://fedoraproject.org/wiki/Zuul-based-ci https://fedora.softwarefactory-project.io/zuul/buildset/747c50c0e8b8490e90a9b06baafad07f
> 
> x [fi-tox-mypy ](https://fedora.softwarefactory-project.io/zuul/build/dcbad7619e824bc0b0f371081041ea9d) **FAILURE** in 6m 29s 
> heavy_check_mark [fi-tox-lint ](https://fedora.softwarefactory-project.io/zuul/build/c3405a3be388475a92d4577f7850c21b) SUCCESS in 8m 42s 
> heavy_check_mark [fi-tox-format ](https://fedora.softwarefactory-project.io/zuul/build/327d612f39344067b9e16f4ad3b429f0) SUCCESS in 9m 01s 
> x [fi-tox-python38 ](https://fedora.softwarefactory-project.io/zuul/build/39c442cb65034e2cac46b19dc6475c11) **FAILURE** in 9m 43s 
> x [fi-tox-python39 ](https://fedora.softwarefactory-project.io/zuul/build/250b4e96baac4ce3aeb446f8f0ece6ef) **FAILURE** in 9m 27s 
> x [fi-tox-python310 ](https://fedora.softwarefactory-project.io/zuul/build/3342b064ae344d20a1c9c75fa3a98e4d) **FAILURE** in 10m 13s 
> x [fi-tox-docs ](https://fedora.softwarefactory-project.io/zuul/build/4d9b5ea5173a4aa6ad6fd12887904e99) **FAILURE** in 9m 55s 
> heavy_check_mark [fi-tox-bandit ](https://fedora.softwarefactory-project.io/zuul/build/05984e592e4b4a85bee9cddacffcff08) SUCCESS in 9m 09s 
> x [fi-tox-diff-cover ](https://fedora.softwarefactory-project.io/zuul/build/0d968ab8ce33436ba0442d308d5eff54) **FAILURE** in 10m 24s

Since I only changed an HTML file, and most of those failures are things like,

> mypy: 295 E failed with could not find python interpreter matching any of the specs python3.9 [tox/session/cmd/run/single.py:55]

I'mma guess that's not my fault.

**Comment by Zlopez** [comment]
You are right, that is not your fault. I need to fix that. Could you also add a news file for this change? See https://anitya.readthedocs.io/en/latest/contributing.html#release-notes for more info.

**Comment by Zlopez** [comment]
I fixed the tests in #1558. Could you rebase this PR to reflect the changes?

**Comment by ferdnyc** [comment]
@Zlopez 
> I fixed the tests in #1558. Could you rebase this PR to reflect the changes?

Done. I also changed the contents significantly.

Playing with it, using `col-md-7` + `col-md-5` overlapped in _fewer_ circumstances, but it still did overlap for some widths. Plus, having different numbers of columns allocated to each side meant that at certain browser widths right around the breakpoint, when they stacked into a single column they were different widths (the bottom (right) end of the stack was narrower than the top (left) end).

But by just removing the fixed widths entirely and setting both columns to simply `col-md`, everything balances out automatically, at any width.

### The original `col-md-5 md-offset-1` / `col-md-5`

col-md-5

### My initial modification, `col-md-7` / `col-md-7`

col-md-7

### `col-md` / `col-md`

col-md


You can see in the third width, of that last 6, that the left column is automatically wider than the right column when necessary. It gets more of the width when it needs it but the right column doesn't.

So, now, that's what this PR does. Commit message updated and `news/` entry added as requested.

**Review by Zlopez — APPROVED** [review]

**Pull request merged**
