### PR TITLE
update Stackage version html regexp (#283)

### PR DESCRIPTION
**Pull request by juhp**
I think this should be sufficient to cover the html changes on stackage.org.

### CODE REVIEW

**Comment by pypingou** [comment]
Isn't this a duplicate of #284 ?

**Comment by juhp** [comment]
Perhaps I am doing this wrong - I thought simpler to start with a new PR: should I PR to the fix_stackage branch instead?

**Comment by juhp** [comment]
Ah, I need to update the tests too I guess. :-(

**Comment by pypingou** [comment]
Well, it's more than if #284 works, then let's go ahead with it, otherwise indeed we can merge your PR :)

**Comment by juhp** [comment]
Okay it is up to you I think: like I say there is only one global html format on stackage.org, so no need really to support the old html.

**Comment by pypingou** [comment]
Ok, then let's go with your PR indeed, mind adjusting the unit-tests then?

Thanks :)

**Comment by juhp** [comment]
I think they should pass now.

**Comment by pypingou** [comment]
Thanks :)

**Pull request merged**
