### PR TITLE
Fixed the stackage backend regex

### PR DESCRIPTION
**Pull request by supzi-del**
Fix the stackage backend regex
Fixes fedora-infra/anitya#1010

### CODE REVIEW

**Review by Zlopez — CHANGES_REQUESTED** [review]
The change looks good, could you add unit tests and [news file](https://anitya.readthedocs.io/en/stable/contributing.html#release-notes)?

**Comment by supzi-del** [comment]
Hey @Zlopez can you tell me how to add unit tests as I'm new to this?

**Comment by Zlopez** [comment]
First, you should fix the failing tests https://travis-ci.org/github/fedora-infra/anitya/builds/760625301?utm_source=github_status&utm_medium=notification

You can test this locally using `tox`. See https://anitya.readthedocs.io/en/latest/contributing.html

Next you should update existing tests in `anitya/tests/lib/backends/test_stackage.py`. You will probably need to just delete existing request data:
https://github.com/fedora-infra/anitya/blob/master/anitya/tests/request-data/anitya.tests.lib.backends.test_stackage.HackageBackendtests.test_get_version
https://github.com/fedora-infra/anitya/blob/master/anitya/tests/request-data/anitya.tests.lib.backends.test_stackage.HackageBackendtests.test_get_versions

And then run the tests again, this will remove the existing VCR data (recorded request/response) and create a new data with correct response.

If you need any other help, let me know.

**Comment by Zlopez** [comment]
I fixed the tests and found out there is a better way to check for new version, so I changed the regex to something different.

**Review by Zlopez — APPROVED** [review]

**Pull request merged**
