### PR TITLE
Feature/prettier flash

### PR DESCRIPTION
**Pull request by oddshocks**
I had tweaked the CSS code a bit while working on feature/flag-project to make the flash messages at the top of the window a bit more readable. Any thoughts on this? Different color? Other criticisms? Happy to tweak it up a bit.

What I did looks like this:
2015-05-07-094351_1270x266_scrot

### CODE REVIEW

**Comment by pypingou** [comment]
How does it do for error message? Do they still appear in red?

**Comment by ralphbean** [comment]
There are totally bootstrap classes that can help here if you can change how the HTML gets written.

**Comment by ralphbean** [comment]
For instance, there are these [contextual panels](http://getbootstrap.com/components/#panels-alternatives) but there's probably a dozen other ways to do it.

**Comment by ralphbean** [comment]
If you accept #153 to get the latest bootstrap Fedora, then you could do the patch like this:


```diff
diff --git a/anitya/app.py b/anitya/app.py
index 4eada72..e17b657 100644
--- a/anitya/app.py
+++ b/anitya/app.py
@@ -75,11 +75,30 @@ def format_examples(examples):
     return output
 
 
+@APP.template_filter('context_class')
+def context_class(category):
+    ''' Return bootstrap context class for a given category. '''
+    values = {
+        'message': 'default',
+        'error': 'danger',
+        'info': 'info',
+
+    }
+    return values.get(category, 'warning')
+
+
 @APP.before_request
 def check_auth():
     ''' Set the flask.g variables using the session information if the user
     is logged in.
     '''
+
+    # Just for testing..
+    flask.flash('this is a default message')
+    flask.flash('error, etc..', 'error')
+    flask.flash('warning', 'warning')
+    flask.flash('info', 'info')
+
     flask.g.auth = Bunch(
         logged_in=False,
         method=None,
diff --git a/anitya/templates/master.html b/anitya/templates/master.html
index de3f486..8e5e5ca 100644
--- a/anitya/templates/master.html
+++ b/anitya/templates/master.html
@@ -158,13 +158,19 @@
 
       {%- with messages = get_flashed_messages(with_categories=true) -%}
         {%- if category, messages -%}
-        <ul id="flashes">
-            {%- for category, message in messages -%}
-            {%- autoescape false -%}
-            <li class="{{ category }}">{{ message }}</li>
-            {%- endautoescape -%}
-            {%- endfor -%}
-        </ul>
+        <div class="container">
+          <div class="row">
+            <div class="col-md-6 col-md-offset-3">
+              <ul id="flashes" class="list-group">
+                  {%- for category, message in messages -%}
+                  {%- autoescape false -%}
+                  <li class="list-group-item list-group-item-{{ category | context_class }}">{{ message }}</li>
+                  {%- endautoescape -%}
+                  {%- endfor -%}
+              </ul>
+            </div>
+          </div>
+        </div>
         {%- endif -%}
       {%- endwith -%}
```


which ends up looking like this:

anitya

**Comment by oddshocks** [comment]
Alright, this looks like it works well and does just what Ralph says. Good to merge?

**Comment by pypingou** [comment]
:+1: for me yes, @ralphbean ok for you?

**Comment by ralphbean** [comment]
LGTM too.  :+1:

**Pull request merged**
